export const enquiryTableData = [
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Bangalore Karnataka',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Ritika',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'Female',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Bangalore Karnataka',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Ritika',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'Female',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Bangalore Karnataka',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Ritika',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'Female',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Bangalore Karnataka',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Ritika',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'Female',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Bangalore Karnataka',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Ritika',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'Female',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Bangalore Karnataka',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Ritika',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'Female',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Bangalore Karnataka',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Ritika',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'Female',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
  ];
  
  export const pendingTableData = [
    {
      name: 'Jay',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Jay',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Jay',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Jay',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
  ];
  
  export const thinkAgainTableData = [
    {
      name: 'Srimoy',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Srimoy',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Srimoy',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Srimoy',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Srimoy',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Srimoy',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
    {
      name: 'Varidh',
      id: 'RT12932',
      class: '8th',
      email: 'emailisemail@gmail.com',
      age: '14',
      address: 'Vrindavan Mathura',
      gender: 'male',
      about:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit Lorem ipsum dolor sit amet consectetur adipisicing elit',
    },
  ];
  